apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zxdm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zxdm
    app.kubernetes.io/part-of: byoc-app-cems
  name: zxdm
spec:
  rules:
  - host: zxdm-byoc-jppn-tenant.apps.fd1e706ac2fb08ce9593.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: zxdm
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
