apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zxdm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zxdm
    app.kubernetes.io/part-of: byoc-app-cems
  name: zxdm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: zxdm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: zxdm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-jppn-tenant/byoc-app-cems/zxdm@sha256:a0297e8d390da5d1d7a03272c201b8a6f862435624065114c0ab39aa97c01caf
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
